export const GET_USER_INFO_INIT = "GET_USER_INFO_INIT"
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED"

export const TOGGLE_BOOKMARD_INIT="TOGGLE_BOOKMARD_INIT"
export const TOGGLE_BOOKMARD_SUCCESS="TOGGLE_BOOKMARD_SUCCESS"
export const TOGGLE_BOOKMARD_FAILED="TOGGLE_BOOKMARD_FAILED"